# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numberBuy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
