# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190329_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
